name: CI+CD

on:
  push:
    branches:
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Clean install
        run: npm ci

      - name: Run production build
        run: npm run build -- --prod
        
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          path: dist/jeroenvogelpoel-nl

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        
      - name: Upload to Azure Storage
        env:
          azure_storage_account: dfwhpersonal
          azure_storage_container: $web
          azure_storage_sas: ${{ secrets.AZURE_STORAGE_SAS }}
        run: |
          shopt -s globstar
          cd artifact
          for file in ** 
          do
            # Skip not regular files
            ! [ -f $file ] && continue;
            
            # Get mime type
            mime_type="text/plain";
            case $file in
              *.js) mime_type="text/javascript";
              *.css) mime_type="text/css";
              *) mime_type=`file $file -b --mime-type`
            esac
            
            # Upload using Azure Storage Blob REST API
            curl -T $file "https://$azure_storage_account.blob.core.windows.net/$azure_storage_container/$file$azure_storage_sas" \
              -H 'x-ms-blob-type: BlockBlob' \
              -H "Content-Type: $mime_type"
           done
